# Generated by Django 4.0.5 on 2022-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=496, unique=True)),
                ('lastName', models.CharField(max_length=992)),
                ('emailAddress', models.EmailField(max_length=992)),
                ('phoneNumber', models.CharField(max_length=76)),
                ('hobbies', models.CharField(default='', max_length=2048)),
                ('validatedEmail', models.BooleanField(default=False)),
                ('validatedNumber', models.BooleanField(default=False)),
            ],
        ),
    ]
